### ISSUE TITLE
Замечания по lw3/task1

### ISSUE THREAD

**Issue by ivklgn** [lifelsbeautiful/web-development-course1#1]
```css
.description {
  margin-left: 220px;

}
.size {
  margin-left: 270px;

}
.quantily{
  margin-left: 70px;
}
.remove{
  margin-left: 170px;
}
.price{
  margin-left: 70px;
}
```

используйте width вместо margin-left

**Comment by ivklgn** [comment]
```css
.shtan {
  height: 120px;
  width: 120px;
  margin: 20px 0 0 100px;
}
```

имя класса непонятно о чем и не на англицком
